# Generated by Django 2.2.11 on 2021-04-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snips', '0002_auto_20210402_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='snip',
            name='description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
