# Generated by Django 2.2.11 on 2021-04-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snips', '0004_auto_20210402_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
